### ISSUE TITLE
ActionSheetStringPicker not showing (Xcode 11.1 Emulator iOS 13)

### ISSUE THREAD

**Issue by coanag** [skywinder/ActionSheetPicker-3.0#430]
ActionSheetStringPicker not showing for project build at Xcode 11.1 iOS 13
Both for Emulator and device.

**Comment by skywinder** [comment]
Hi, I didn't check it for a long time, since not in iOS development anymore. But I do my best to make this project alive. 
Please, let me know, how to fix it. 
I'm also would be glad for any help with this project. So if you are wondering about maintaining this project - please, let me know!
Here is a request topic, that I create about this: #348

**Comment by BubiDevs** [comment]
iOS 13 has some breaking changes on UIWindow management.

PP #425 should solve the problem. Could you please try?

**Comment by skywinder** [comment]
Hello. please check the latest version. Should be fixed. 
Feel free to reopen the issue, if you still need help. 👍

FIxed by #425
