### ISSUE TITLE
iOS 14 unable to select date in inline datePickerStyle

### ISSUE THREAD

**Issue by ivan-magda** [skywinder/ActionSheetPicker-3.0#505]
After #502 (Added background tap gesture to dismiss picker view - Background tap issue) clicks on date in the calendar dismisses the action sheet in `UIDatePicker.Mode.date` and `UIDatePicker.Mode.dateAndTime` modes.

https://github.com/skywinder/ActionSheetPicker-3.0/pull/502/files#diff-5334c1a36535b23b6b5af4fb0b6712f5R261-R267

The documentation of the [UIGestureRecognizerDelegate.gestureRecognizer(_:shouldReceive:)](https://developer.apple.com/documentation/uikit/uigesturerecognizerdelegate/1624214-gesturerecognizer?language=objc) stands out that you should return YES (the default) to allow the gesture recognizer to examine the touch object, NO to prevent the gesture recognizer from seeing this touch object.

**Comment by noorulain17** [comment]
@ivan-magda do you also face this issue in `UIDatePicker.Mode.time` mode too?

The `Gesture Delegate` is returning `NO` for those views where the sheet is visible (by comparing the `viewTag`, because the bottom touch shouldn't dismiss the sheet, only the touch at the top translucent view should dismiss the view.

**Comment by ivan-magda** [comment]
@noorulain17 `UIDatePicker.Mode.time` mode works well.

**Comment by noorulain17** [comment]
Hmm.. Technically all modes should have the problem. Thanks for reporting, I'll look into this.

**Comment by noorulain17** [comment]
Fixed in #514
